# Generated by Django 6.0.1 on 2026-01-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rarity', models.CharField(max_length=1)),
                ('path', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('image', models.SlugField(max_length=300)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
