# Generated by Django 6.0.1 on 2026-02-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='path',
            field=models.CharField(max_length=15),
        ),
    ]
